name: Deploy Personal Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.81.0"

      - name: "Build Hugo curtis.wales"
        id: build
        working-directory: ./curtis.wales
        run: hugo --minify

      - name: "Build Hugo curtis.cymru"
        id: build
        working-directory: ./curtis.cymru
        run: hugo --minify

      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Upload to curtis.wales
        run: gsutil -h "Cache-Control:public, max-age=31536000" cp -r ./curtis.wales/public/* gs://www.curtis.wales
      - name: Upload to curtis.cymru
        run: gsutil -h "Cache-Control:public, max-age=31536000" cp -r ./curtis.cymru/public/* gs://www.curtis.cymru
